# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: certificati
---
# Secret per il registry privato
#
# Il docente lo ha configurato nel cluster.
# Non Ã¨ necessario fare altro
#
#---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcrt
  namespace: certificati
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcrt
  template:
    metadata:
      labels:
        app: testcrt
    spec:
      imagePullSecrets:
        - name: rt-devops-registry-01
      containers:
        - name: testcrt
          image: registry.digitalocean.com/rt-devops-registry-01/team_b-testcrt:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: testcrt
  namespace: certificati
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
